#!/bin/sh /etc/rc.common
# WigleWRT BLE Service - Always running for mobile monitoring

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/wiglewrt-ble

start_service() {
    procd_open_instance
    procd_set_param command python3 "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/wiglewrt-ble.pid
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "wiglewrt"
}
